<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $creator
 */
class Post extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'creator'], 'required'],
            [['creator'], 'integer'],
            [['title'], 'string', 'max' => 64],
            [['description'], 'string', 'max' => 128],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('main', 'ID'),
            'title' => Yii::t('main', 'Title'),
            'description' => Yii::t('main', 'Description'),
            'creator' => Yii::t('main', 'Creator'),
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $this->creator = Yii::$app->user->id;
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}
