<?php
/**
 * Created by PhpStorm.
 * User: Davron
 * Date: 2018/02/05
 * Time: 22:48
 */

namespace common\models;


class StudentModel extends Student
{
    public $username;
    public $password;

    public function rules()
    {
        $rules = parent::rules();
        array_merge([
           $rules,
            [

            ]
        ]);
        return ; // TODO: Change the autogenerated stub
    }
}