<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "times".
 *
 * @property int $id
 * @property int $parent_id
 * @property int $weekday
 * @property int $time
 * @property int $type
 * @property int $status
 */
class Times extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */

    const STATUS_ACTIVE = 1;
    const STATUS_NOT_ACTIVE = 0;

    const TYPE_STUDENT = 1;
    const TYPE_TEACHER = 2;
    const TYPE_GROUP =3;

    public static function tableName()
    {
        return 'times';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'weekday', 'time', 'type', 'status'], 'required'],
            [['parent_id', 'weekday', 'time', 'type', 'status'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('main', 'ID'),
            'parent_id' => Yii::t('main', 'Parent ID'),
            'weekday' => Yii::t('main', 'Weekday'),
            'time' => Yii::t('main', 'Time'),
            'type' => Yii::t('main', 'Type'),
            'status' => Yii::t('main', 'Status'),
        ];
    }

    public static function getByParentAndType($parent, $type) {
        $models = Times::find()->select(['weekday','time'])->andFilterWhere(['parent_id' => $parent, 'type' => $type, 'status' => Times::STATUS_ACTIVE])->asArray()->all();
        return $models;
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        if($this->isNewRecord)
            $this->status = Times::STATUS_ACTIVE;

        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    public static function hasTime($times, $weekday, $hour) {
        foreach ($times as $time) {
            if($time['weekday'] == $weekday && $time['time'] == $hour)
                return true;
        }
        return false;
    }
}
